{ pkgs
, ffiLibraryName
, flutterBridgeDir
# Platform-specific builders. The composer only consumes their public outputs:
#   androidBuilder = { abi; package; }
#   nativeBuilder = { libDir; package; }
, androidBuilder
, nativeBuilder
, dartFfiGenerator ? (import ./tools.nix { inherit pkgs; }).dartFfiGenerator
, manifestFile ? "ffi-manifest.json"
, ffiPackageDir ? "haskell-ffi"
, ffiPackageFile
, localHaskellPackages
, packagesToRegenerate ? null
, dartApiFile ? "bridge.dart"
}:

let
  # `regen-haskell-nix` regenerates cabal2nix files for source packages that are
  # maintained together with the Flutter project. External packages can opt out
  # with `regenerate = false`.
  localPackagesToRegenerate =
    pkgs.lib.mapAttrsToList
      (packageName: localPackage: {
        packageDir = localPackage.packageDir or packageName;
        outputFile =
          localPackage.outputFile or (builtins.baseNameOf localPackage.packageFile);
      })
      (pkgs.lib.filterAttrs
        (_: localPackage: localPackage.regenerate or true)
        localHaskellPackages);

  # The root FFI adapter is always regenerated by default because it is the
  # package that exports the symbols used to generate the Dart API.
  ffiPackageToRegenerate = {
    packageDir = ffiPackageDir;
    outputFile = builtins.baseNameOf ffiPackageFile;
  };

  defaultPackagesToRegenerate =
    localPackagesToRegenerate ++ [ ffiPackageToRegenerate ];

  effectivePackagesToRegenerate =
    if packagesToRegenerate == null then
      defaultPackagesToRegenerate
    else
      packagesToRegenerate;

  copyAndroidArtifacts = ''
    jni_libs="$(nix build --no-link --print-out-paths .#android-jni-libs)"
    dart_api_manifest="$jni_libs/${manifestFile}"

    target_dir="${flutterBridgeDir}/android/src/main/jniLibs/${androidBuilder.abi}"
    if [ -e "$target_dir" ]; then
      chmod -R u+w "$target_dir"
      rm -rf "$target_dir"
    fi
    mkdir -p "$(dirname "$target_dir")"
    cp -R "$jni_libs/${androidBuilder.abi}" "$target_dir"
    chmod -R u+w "$target_dir"
  '';

  copyNativeArtifacts = ''
    native_libs="$(nix build --no-link --print-out-paths .#native-shared-libs)"
    if [ "$mode" = native ]; then
      dart_api_manifest="$native_libs/${manifestFile}"
    fi

    native_target_dir="${nativeBuilder.libDir}"
    if [ -e "$native_target_dir" ]; then
      chmod -R u+w "$native_target_dir"
      rm -rf "$native_target_dir"
    fi
    mkdir -p "$native_target_dir"
    cp -R "$native_libs/lib/." "$native_target_dir/"
    chmod -R u+w "$native_target_dir"
  '';

  packages = rec {
    android-jni-libs = androidBuilder.package;

    native-shared-libs = nativeBuilder.package;

    dart-api =
      pkgs.runCommand "${ffiLibraryName}-dart-api" { } ''
        mkdir -p "$out"
        ${dartFfiGenerator}/bin/flutter-haskell-generate-dart-ffi \
          --spec ${android-jni-libs}/${manifestFile} \
          --out "$out/${dartApiFile}"
      '';

    default = android-jni-libs;
  };

  regenScript =
    let
      regenerateCommand = package:
        if builtins.isAttrs package then
          "regenerate ${pkgs.lib.escapeShellArg package.packageDir} ${pkgs.lib.escapeShellArg package.outputFile}"
        else
          "regenerate ${pkgs.lib.escapeShellArg package} \"$(basename ${pkgs.lib.escapeShellArg package}).nix\"";
    in
    pkgs.writeShellScriptBin "regen-haskell-nix" ''
      set -euo pipefail

      regenerate() {
        local package="$1"
        local output_file="$2"
        mkdir -p "$package/nix/generated"
        (
          cd "$package/nix/generated"
          ${pkgs.cabal2nix}/bin/cabal2nix ../.. > "$output_file"
        )
      }

      ${pkgs.lib.concatMapStringsSep "\n" regenerateCommand effectivePackagesToRegenerate}
    '';

  bundleLibsScript =
    pkgs.writeShellScriptBin "bundle-libs" ''
      set -euo pipefail

      mode="''${1:-all}"
      case "$mode" in
        all|android|native)
          ;;
        *)
          echo "usage: bundle-libs [all|android|native]" >&2
          exit 2
          ;;
      esac

      ${regenScript}/bin/regen-haskell-nix

      dart_api_manifest=
      if [ "$mode" = all ] || [ "$mode" = android ]; then
        ${copyAndroidArtifacts}
      fi

      if [ "$mode" = all ] || [ "$mode" = native ]; then
        ${copyNativeArtifacts}
      fi

      dart_api_dir="$(mktemp -d)"
      ${dartFfiGenerator}/bin/flutter-haskell-generate-dart-ffi \
        --spec "$dart_api_manifest" \
        --out "$dart_api_dir/${dartApiFile}"
      cp "$dart_api_dir/${dartApiFile}" \
        "${flutterBridgeDir}/lib/${dartApiFile}"
    '';
in
{
  inherit packages;

  apps = {
    regen-haskell-nix = {
      type = "app";
      program = "${regenScript}/bin/regen-haskell-nix";
    };

    bundle-libs = {
      type = "app";
      program = "${bundleLibsScript}/bin/bundle-libs";
    };
  };
}
